// Generated by CoffeeScript 2.5.1
var numbers, reaultA, reaultB, reaultC;

const jslinq = require('../src');

numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

reaultA = jslinq(numbers).Any(function (value) {
  return value % 2 === 0;
});

reaultB = jslinq(numbers).Any(function (value) {
  return value >= 10;
});

reaultC = jslinq(numbers).Any(function (value) {
  return value < 5;
});

console.log('reaultA:', reaultA);

console.log('reaultB:', reaultB);

console.log('reaultC:', reaultC);
