// Generated by CoffeeScript 2.5.1
var jslinq, orderedParameters, parameters;

jslinq = require('../linqjs/linq');

parameters = [
  {
    ID: 0,
    Name: '正一郎'
  },
  {
    ID: 3,
    Name: '清次郎'
  },
  {
    ID: 2,
    Name: '誠三郎'
  },
  {
    ID: 5,
    Name: '征史郎'
  }
];

console.log('parameters:', parameters);

orderedParameters = jslinq(parameters)
  .OrderByDescending(function (value) {
    return value.ID;
  })
  .ToArray();

console.log('parameters:', parameters);
console.log('orderedParameters:', orderedParameters);
