// Generated by CoffeeScript 2.5.1
var jslinq, numbers;

jslinq = require('../linqcs').jslinq;

numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

new jslinq(numbers).Remove(6);

console.log(numbers);

console.log(numbers.length);
