// Generated by CoffeeScript 2.5.1
var jslinq, parameters, results;

jslinq = require('../linqjs/linq');

parameters = [
  {
    Name: '正一郎',
    Numbers: [1, 2, 3]
  },
  {
    Name: '清次郎',
    Numbers: [1, 3, 5]
  },
  {
    Name: '誠三郎',
    Numbers: [2, 4, 6]
  },
  {
    Name: '征史郎',
    Numbers: [9, 8, 7]
  }
];

results = jslinq(parameters)
  .SelectMany(x => jslinq(x.Numbers))
  .ToArray();

console.log('results:', results);

console.log('results:', results.length);
