// Generated by CoffeeScript 2.5.1
var ageSum, jslinq, parameters;

jslinq = require('../linqcs').jslinq;

parameters = [
  {
    Age: 52,
    Name: "正一郎"
  },
  {
    Age: 28,
    Name: "清次郎"
  },
  {
    Age: 20,
    Name: "誠三郎"
  },
  {
    Age: 18,
    Name: "征史郎"
  }
];

ageSum = new jslinq(parameters).Sum(function(value) {
  return value.Age;
});

console.log('ageSum:', ageSum);
