// Generated by CoffeeScript 2.5.1
var jslinq, numbers, takenNumbers, takenTexts, texts;

jslinq = require('../linqcs').jslinq;

numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

texts = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

// 开始的3个
takenNumbers = new jslinq(numbers).Take(3).ToArray();

// 开始的4个
takenTexts = new jslinq(texts).Take(4).ToArray();

console.log('takenNumbers:', takenNumbers);

console.log('takenTexts:', takenTexts);
